name: Binary File Change and New Binary Detection Example Repo

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write

jobs:
  binary-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run binary file detection action
        uses: lucasbalieiro/binary-x9@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
