name: Binary File Change and New Binary Detection

on:
  pull_request:
    branches:
      - main
jobs:
  binary-change-warning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Detect binary file changes and new binary files
      id: detect_changes
      run: |
        binary_extensions=("*.so" "*.tar.gz" "*.taz.gz" "*.zip" "*.exe" "*.dll" "*.dylib" "*.bin" "*.apk" "*.ipa" "*.deb" "*.rpm" "*.msi")
        git fetch origin ${{ github.event.pull_request.base.ref }}
        changed_files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD)
        new_files=""
        binary_changed=false

        for ext in "${binary_extensions[@]}"; do
          if echo "$changed_files" | grep -qE "${ext//./\\.}$"; then
            binary_changed=true
            new_files=$(echo "$changed_files" | grep -E "${ext//./\\.}$")
            break
          fi
        done

        echo "binary_changed=$binary_changed" >> $GITHUB_ENV
        echo "new_files=$new_files" >> $GITHUB_ENV

    - name: Add PR comment if binary files changed or new binaries added
      if: env.binary_changed == 'true'
      run: |
        COMMENT_BODY="### ⚠️ Warning: Binary File Changed or Added! ⚠️\n\n"

        # Add information about the modified or newly added binary file(s)
        COMMENT_BODY="${COMMENT_BODY}This PR has modified or added the following binary file(s):\n\n"
        for file in $(echo $new_files | tr ' ' '\n'); do
          COMMENT_BODY="${COMMENT_BODY}- \`$file\`\n"
        done

        COMMENT_BODY="${COMMENT_BODY}\nWhile these changes may be intentional, please ensure that a thorough review is conducted to avoid any potential issues or backdoors."

        # Post the comment on the PR
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -X POST \
          -d "{\"body\": \"$COMMENT_BODY\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
